server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 5MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
keycloak:
  url: http://localhost:8002/auth
  realm: master
  client-id: user-service-client
  client-secret: uxfjcmFmnMH7l7Ui0grOiyOTj9sVaebZ
  grand-type: password
  username: admin
  password: 12345

minio:
  url: http://minio-file-service:9000
  username: admin
  password: admin123
  bucket: users-photos
